import { Inter } from "next/font/google";
// import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="/assets/css/app.min.css"/>
      {/* <!-- Template CSS --> */}
      <link rel="stylesheet" href="/assets/css/style.css"/>
      <link rel="stylesheet" href="/assets/css/components.css"/>
      {/* <!-- Custom style CSS --> */}
      <link rel="stylesheet" href="/assets/css/custom.css"/>
      {/* <link rel="stylesheet" href="/assets/bundles/material-icons/MaterialIcons-Regular.woff2" /> */}
      </head>
      <body className={`${inter.className} light light-sidebar theme-white`}>{children}</body>
    </html>
  );
}
